# Generated by Django 3.0.4 on 2020-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'bkinfo',
            },
        ),
        migrations.CreateModel(
            name='issbktb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=50)),
                ('bkname', models.CharField(max_length=50)),
                ('issbkdt', models.DateField(auto_now_add=True)),
                ('retdt', models.DateField(null=True)),
                ('fine', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'issbkinfo',
            },
        ),
        migrations.CreateModel(
            name='Newstu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('stu_class', models.IntegerField()),
            ],
            options={
                'db_table': 'stuinfo',
            },
        ),
    ]
