# Generated by Django 3.0.6 on 2020-11-28 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facultyapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bkinfo',
            },
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cnt', models.IntegerField(blank=True, unique=True)),
                ('sub', models.CharField(max_length=250)),
                ('msg', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='issbktb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_enroll', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('b_name', models.CharField(max_length=50)),
                ('b_id', models.CharField(max_length=50)),
                ('issbkdt', models.DateField(auto_now_add=True)),
                ('expirydt', models.DateField(default=facultyapp.models.get_expiry)),
                ('fine', models.IntegerField()),
            ],
            options={
                'db_table': 'issbkinfo',
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d')),
                ('age', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(default='Male', max_length=250)),
                ('enrollment', models.CharField(blank=True, max_length=40, null=True)),
                ('branch', models.CharField(blank=True, max_length=40, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
