# Generated by Django 3.0.6 on 2020-11-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issbktb',
            name='fine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
